### PR TITLE
pull from / eligrey / Blob.js

### PR DESCRIPTION
**Pull request by fschai89**
The Blob.js is outdated, please pull the update from eligrey. Thanks.

### CODE REVIEW

**Comment by bjornstar** [comment]
Not sure what you're trying to accomplish here, but there hasn't been any change worth porting since the big one on April 20th of last year which I did port.

**Comment by fschai89** [comment]
Hi @bjornstar ,

this is because I get error when using your Blob.js but working fine if using Blog.js from eligrey

`Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:582)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:17)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:20)
    at Object.eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:685)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:691)
    at Object../node_modules/blob-polyfill/Blob.js (index.82529ee77b51da7e15dc.bundle.js:1990)
    at __webpack_require__ (index.82529ee77b51da7e15dc.bundle.js:726)
    at fn (index.82529ee77b51da7e15dc.bundle.js:101)
    at Object.0 (index.82529ee77b51da7e15dc.bundle.js:13218)
    at __webpack_require__ (index.82529ee77b51da7e15dc.bundle.js:726)`

**Comment by bjornstar** [comment]
When used as an AMD or CommonJS module, blob-polyfill does not modify the global namespace. You can take a look at https://webpack.js.org/guides/shimming/ for more information on how to configure webpack to use blob-polyfill as a global. I will echo their recommendation:

>We don't recommend using globals! The whole concept behind webpack is to allow more modular front-end development. This means writing isolated modules that are well contained and do not rely on hidden dependencies (e.g. globals). Please use these features only when necessary.

You can use blob-polyfill as a module like this:

``` js
const Blob = require('blob-polyfill').Blob;
````

Or using ES6 module syntax:

```js
import { Blob } from 'blob-polyfill';
```

**Comment by fschai89** [comment]
@bjornstar 

I tried to use as import only but still get error on line 585

exports.File.prototype[strTag] = "File";

`Blob.js?a51f:585 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.eval (Blob.js?a51f:585)
    at eval (Blob.js?a51f:15)
    at eval (Blob.js?a51f:23)
    at Object.eval (Blob.js?a51f:688)
    at eval (Blob.js:692)
    at Object../node_modules/blob-polyfill/Blob.js (index.fc0e7602232d5b68132e.bundle.js:1990)
    at __webpack_require__ (index.fc0e7602232d5b68132e.bundle.js:726)
    at fn (index.fc0e7602232d5b68132e.bundle.js:101)
    at eval (FileAction.js?c429:8)
    at Object../src/modules/File/FileAction.js (index.fc0e7602232d5b68132e.bundle.js:12953)`

**Comment by bjornstar** [comment]
Is this in some kind of browser?

**Comment by fschai89** [comment]
@bjornstar Chrome browser, tried on Safari also same error.

**Comment by bjornstar** [comment]
I published a `v4.0.20200531` that should fix the issue with the readonly property getting set.

Please give it a try.

**Comment by fschai89** [comment]
hi @bjornstar,
Thanks, appreciate for your effort to fix, but I still facing the error
`Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:582)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:17)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:20)
    at Object.eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:685)
    at eval (webpack-internal:///./node_modules/blob-polyfill/Blob.js:692)
    at Object../node_modules/blob-polyfill/Blob.js (index.912549a1abe16741c2cb.bundle.js:1990)
    at __webpack_require__ (index.912549a1abe16741c2cb.bundle.js:726)
    at fn (index.912549a1abe16741c2cb.bundle.js:101)
    at eval (webpack-internal:///./src/modules/File/FileAction.js:29)`

**Comment by bjornstar** [comment]
I was able to reproduce your issue locally and I have published `v4.0.20200601` with a fix.

I hope it works for you.

**Pull request closed without merging**
